{{- if and .Values.api.enabled .Values.api.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "forge.fullname" . }}-api
  labels:
    {{- include "forge.componentLabels" (dict "ctx" . "component" "api") | nindent 4 }}
spec:
  minAvailable: {{ .Values.api.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "forge.componentSelectorLabels" (dict "ctx" . "component" "api") | nindent 6 }}
{{- end }}
