"""Forge SQLAlchemy models — the shared data-model substrate.

Importing this package registers every model on ``Base.metadata`` (used by
Alembic's ``env.py`` and by ``Base.metadata.create_all`` in tests).
"""

from __future__ import annotations

from forge_db.models import enums
from forge_db.models.ao_settings import AoWorkspaceSettings
from forge_db.models.approval import ApprovalDecision, PolicyOverrideGrant
from forge_db.models.audit import AuditChainHead, AuditLog, AuditLogImmutableError
from forge_db.models.automation import AutomationExecution, AutomationRule
from forge_db.models.benchmark import BenchmarkSubmission, BenchmarkSuite
from forge_db.models.connections import MCPConnection, RepositoryConnection
from forge_db.models.cost import CostEvent, ModelPrice
from forge_db.models.deployment import (
    Deployment,
    DeploymentApproval,
    DeploymentCheckResult,
    DeploymentTransition,
    Environment,
    EnvironmentPipeline,
)
from forge_db.models.enums import (
    AccessLevel,
    AgentRole,
    APIKeyKind,
    ApprovalGate,
    ApprovalStatus,
    AutomationActionType,
    AutomationEntityType,
    AutomationExecutionStatus,
    AutomationTriggerSource,
    AutomationTriggerType,
    ChunkType,
    CostEventKind,
    DeploymentEventType,
    DeploymentKind,
    DeploymentState,
    DeploymentTrigger,
    Effort,
    EngineBackend,
    ExecutionMode,
    ExternalIdentityProvider,
    GateCheckName,
    GateCheckStatus,
    HealthStatus,
    IncidentSeverity,
    IncidentState,
    KnowledgeSourceKind,
    MCPAuthType,
    MCPIndexStrategy,
    MCPTransport,
    OAuthProvider,
    PlatformKeyKind,
    PMAuthType,
    PMConflictPolicy,
    PMConnectionStatus,
    PMDeliveryStatus,
    PMProvider,
    PMSyncDirection,
    PMSyncState,
    PRGroupStatus,
    PrincipalType,
    Priority,
    PRMergeState,
    ProjectVisibility,
    RepoProvider,
    RepoRole,
    RunStatus,
    SandboxKind,
    SandboxNetwork,
    SandboxStatus,
    ScimResourceType,
    ScopeType,
    SpecStatus,
    SsoProtocol,
    SyncMode,
    TaskKind,
    TaskStatus,
    TeamRole,
    UserRole,
    WorkflowState,
)
from forge_db.models.idempotency import IdempotencyKey
from forge_db.models.incidents import (
    IncidentAlert,
    IncidentEvent,
    Postmortem,
    PostmortemActionItem,
    RemediationPlan,
)
from forge_db.models.knowledge import (
    CHUNK_TYPE_WEIGHTS,
    EMBEDDING_DIM,
    KnowledgeSource,
    RetrievalChunk,
)
from forge_db.models.marketplace import (
    MarketplaceAuditLog,
    MarketplaceInstallation,
    MarketplaceListing,
    MarketplaceListingVersion,
    MarketplaceRegistry,
)
from forge_db.models.mcp_index import (
    KnowledgeSyncRun,
    MCPIndexedResource,
)
from forge_db.models.multi_repo import AgentRepoWorkspace, PRGroup
from forge_db.models.oauth_account import OAuthAccount
from forge_db.models.observability_audit import (
    ObservabilityAuditChainHead,
    ObservabilityAuditEntry,
)
from forge_db.models.planning import (
    Epic,
    Incident,
    Milestone,
    SpecDocument,
    Sprint,
    Task,
    TaskDependency,
)
from forge_db.models.platform_api_key import PlatformAPIKey
from forge_db.models.pm import PMConnection, PMTaskLink, PMWebhookDelivery
from forge_db.models.policy_rule_evaluation import PolicyRuleEvaluation
from forge_db.models.profiles import PolicyProfile, SkillProfile
from forge_db.models.project import Constitution, Project
from forge_db.models.project_team_access import ProjectTeamAccess
from forge_db.models.role_config import AgentRoleConfig
from forge_db.models.role_grant import RoleGrant
from forge_db.models.runs import AgentRun, ApprovalRequest, SubAgentRun, WorkflowRun
from forge_db.models.sandbox import SandboxInstance
from forge_db.models.secret import Secret
from forge_db.models.sprint_velocity import (
    SprintBurndownSnapshot,
    SprintScopeEvent,
    SprintVelocity,
)
from forge_db.models.sso import (
    ExternalIdentity,
    SamlReplay,
    ScimGroup,
    ScimGroupMember,
    ScimToken,
    SsoConfiguration,
    SsoDomain,
)
from forge_db.models.team import Team
from forge_db.models.team_member import TeamMember
from forge_db.models.traceability import (
    TraceabilityCriterionLink,
    TraceabilitySpecRollup,
)
from forge_db.models.workflow_editor import (
    RevisionStatus,
    RevisionValidationStatus,
    WorkflowDefinition,
    WorkflowDefinitionRevision,
    WorkflowDefinitionSource,
)
from forge_db.models.workspace import APIKey, User, Workspace

__all__ = [
    "CHUNK_TYPE_WEIGHTS",
    "EMBEDDING_DIM",
    "APIKey",
    "APIKeyKind",
    "AccessLevel",
    "AgentRepoWorkspace",
    "AgentRole",
    "AgentRoleConfig",
    "AgentRun",
    "AoWorkspaceSettings",
    "ApprovalDecision",
    "ApprovalGate",
    "ApprovalRequest",
    "ApprovalStatus",
    "AuditChainHead",
    "AuditLog",
    "AuditLogImmutableError",
    "AutomationActionType",
    "AutomationEntityType",
    "AutomationExecution",
    "AutomationExecutionStatus",
    "AutomationRule",
    "AutomationTriggerSource",
    "AutomationTriggerType",
    "BenchmarkSubmission",
    "BenchmarkSuite",
    "ChunkType",
    "Constitution",
    "CostEvent",
    "CostEventKind",
    "Deployment",
    "DeploymentApproval",
    "DeploymentCheckResult",
    "DeploymentEventType",
    "DeploymentKind",
    "DeploymentState",
    "DeploymentTransition",
    "DeploymentTrigger",
    "Effort",
    "EngineBackend",
    "Environment",
    "EnvironmentPipeline",
    "Epic",
    "ExecutionMode",
    "ExternalIdentity",
    "ExternalIdentityProvider",
    "GateCheckName",
    "GateCheckStatus",
    "HealthStatus",
    "IdempotencyKey",
    "Incident",
    "IncidentAlert",
    "IncidentEvent",
    "IncidentSeverity",
    "IncidentState",
    "KnowledgeSource",
    "KnowledgeSourceKind",
    "KnowledgeSyncRun",
    "MCPAuthType",
    "MCPConnection",
    "MCPIndexStrategy",
    "MCPIndexedResource",
    "MCPTransport",
    "MarketplaceAuditLog",
    "MarketplaceInstallation",
    "MarketplaceListing",
    "MarketplaceListingVersion",
    "MarketplaceRegistry",
    "Milestone",
    "ModelPrice",
    "OAuthAccount",
    "OAuthProvider",
    "ObservabilityAuditChainHead",
    "ObservabilityAuditEntry",
    "PMAuthType",
    "PMConflictPolicy",
    "PMConnection",
    "PMConnectionStatus",
    "PMDeliveryStatus",
    "PMProvider",
    "PMSyncDirection",
    "PMSyncState",
    "PMTaskLink",
    "PMWebhookDelivery",
    "PRGroup",
    "PRGroupStatus",
    "PRMergeState",
    "PlatformAPIKey",
    "PlatformKeyKind",
    "PolicyOverrideGrant",
    "PolicyProfile",
    "PolicyRuleEvaluation",
    "Postmortem",
    "PostmortemActionItem",
    "PrincipalType",
    "Priority",
    "Project",
    "ProjectTeamAccess",
    "ProjectVisibility",
    "RemediationPlan",
    "RepoProvider",
    "RepoRole",
    "RepositoryConnection",
    "RetrievalChunk",
    "RevisionStatus",
    "RevisionValidationStatus",
    "RoleGrant",
    "RunStatus",
    "SamlReplay",
    "SandboxInstance",
    "SandboxKind",
    "SandboxNetwork",
    "SandboxStatus",
    "ScimGroup",
    "ScimGroupMember",
    "ScimResourceType",
    "ScimToken",
    "ScopeType",
    "Secret",
    "SkillProfile",
    "SpecDocument",
    "SpecStatus",
    "Sprint",
    "SprintBurndownSnapshot",
    "SprintScopeEvent",
    "SprintVelocity",
    "SsoConfiguration",
    "SsoDomain",
    "SsoProtocol",
    "SubAgentRun",
    "SyncMode",
    "Task",
    "TaskDependency",
    "TaskKind",
    "TaskStatus",
    "Team",
    "TeamMember",
    "TeamRole",
    "TraceabilityCriterionLink",
    "TraceabilitySpecRollup",
    "User",
    "UserRole",
    "WorkflowDefinition",
    "WorkflowDefinitionRevision",
    "WorkflowDefinitionSource",
    "WorkflowRun",
    "WorkflowState",
    "Workspace",
    "enums",
]
