"""Forge SQLAlchemy models — the shared data-model substrate.

Importing this package registers every model on ``Base.metadata`` (used by
Alembic's ``env.py`` and by ``Base.metadata.create_all`` in tests).
"""

from __future__ import annotations

from forge_db.models import enums
from forge_db.models.automation import AutomationExecution, AutomationRule
from forge_db.models.connections import MCPConnection, RepositoryConnection
from forge_db.models.enums import (
    APIKeyKind,
    ApprovalGate,
    ApprovalStatus,
    AutomationActionType,
    AutomationEntityType,
    AutomationExecutionStatus,
    AutomationTriggerSource,
    AutomationTriggerType,
    ChunkType,
    ExecutionMode,
    IncidentSeverity,
    IncidentState,
    KnowledgeSourceKind,
    MCPAuthType,
    MCPIndexStrategy,
    MCPTransport,
    PMAuthType,
    PMConflictPolicy,
    PMConnectionStatus,
    PMDeliveryStatus,
    PMProvider,
    PMSyncDirection,
    PMSyncState,
    PRGroupStatus,
    Priority,
    PRMergeState,
    RepoProvider,
    RepoRole,
    RunStatus,
    SandboxKind,
    SandboxNetwork,
    SandboxStatus,
    SpecStatus,
    SyncMode,
    TaskKind,
    TaskStatus,
    UserRole,
    WorkflowState,
)
from forge_db.models.incidents import (
    IncidentAlert,
    IncidentEvent,
    Postmortem,
    PostmortemActionItem,
    RemediationPlan,
)
from forge_db.models.knowledge import (
    CHUNK_TYPE_WEIGHTS,
    EMBEDDING_DIM,
    KnowledgeSource,
    RetrievalChunk,
)
from forge_db.models.mcp_index import (
    KnowledgeSyncRun,
    MCPIndexedResource,
)
from forge_db.models.multi_repo import AgentRepoWorkspace, PRGroup
from forge_db.models.planning import (
    Epic,
    Incident,
    Milestone,
    SpecDocument,
    Sprint,
    Task,
)
from forge_db.models.pm import PMConnection, PMTaskLink, PMWebhookDelivery
from forge_db.models.profiles import PolicyProfile, SkillProfile
from forge_db.models.project import Constitution, Project
from forge_db.models.runs import AgentRun, ApprovalRequest, SubAgentRun, WorkflowRun
from forge_db.models.sandbox import SandboxInstance
from forge_db.models.workspace import APIKey, User, Workspace

__all__ = [
    "CHUNK_TYPE_WEIGHTS",
    "EMBEDDING_DIM",
    "APIKey",
    "APIKeyKind",
    "AgentRepoWorkspace",
    "AgentRun",
    "ApprovalGate",
    "ApprovalRequest",
    "ApprovalStatus",
    "AutomationActionType",
    "AutomationEntityType",
    "AutomationExecution",
    "AutomationExecutionStatus",
    "AutomationRule",
    "AutomationTriggerSource",
    "AutomationTriggerType",
    "ChunkType",
    "Constitution",
    "Epic",
    "ExecutionMode",
    "Incident",
    "IncidentAlert",
    "IncidentEvent",
    "IncidentSeverity",
    "IncidentState",
    "KnowledgeSource",
    "KnowledgeSourceKind",
    "KnowledgeSyncRun",
    "MCPAuthType",
    "MCPConnection",
    "MCPIndexStrategy",
    "MCPIndexedResource",
    "MCPTransport",
    "Milestone",
    "PMAuthType",
    "PMConflictPolicy",
    "PMConnection",
    "PMConnectionStatus",
    "PMDeliveryStatus",
    "PMProvider",
    "PMSyncDirection",
    "PMSyncState",
    "PMTaskLink",
    "PMWebhookDelivery",
    "PRGroup",
    "PRGroupStatus",
    "PRMergeState",
    "PolicyProfile",
    "Postmortem",
    "PostmortemActionItem",
    "Priority",
    "Project",
    "RemediationPlan",
    "RepoProvider",
    "RepoRole",
    "RepositoryConnection",
    "RetrievalChunk",
    "RunStatus",
    "SandboxInstance",
    "SandboxKind",
    "SandboxNetwork",
    "SandboxStatus",
    "SkillProfile",
    "SpecDocument",
    "SpecStatus",
    "Sprint",
    "SubAgentRun",
    "SyncMode",
    "Task",
    "TaskKind",
    "TaskStatus",
    "User",
    "UserRole",
    "WorkflowRun",
    "WorkflowState",
    "Workspace",
    "enums",
]
