{{- if and .Values.worker.enabled .Values.worker.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "forge.fullname" . }}-worker
  labels:
    {{- include "forge.componentLabels" (dict "ctx" . "component" "worker") | nindent 4 }}
spec:
  minAvailable: {{ .Values.worker.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "forge.componentSelectorLabels" (dict "ctx" . "component" "worker") | nindent 6 }}
{{- end }}
