"""Authenticated encryption for secrets at rest (Task 1.15 — auth & secrets).

Spec Security: "Secrets — Encrypted at rest". The plan calls for a Fernet /
libsodium-backed vault. Those libraries are not present in this build sandbox and
``uv sync`` is disallowed here, so the *default, fully-tested* cipher is built on
the Python standard library only:

    blob = version(1) || nonce(16) || tag(32) || ciphertext

- Confidentiality: a keystream is generated by HMAC-SHA256 in counter mode
  (``HMAC(enc_key, nonce || counter)``) and XORed with the plaintext.
- Integrity: encrypt-then-MAC with an independent key
  (``tag = HMAC(mac_key, version || nonce || ciphertext)``), verified in constant
  time before any decryption output is produced.
- Key separation: ``enc_key`` and ``mac_key`` are derived per-message from the
  master key and the random nonce (HKDF-Expand-style single block), so keys are
  never reused across messages.

This is genuine authenticated encryption: ciphertext never contains the
plaintext, tampering or a wrong key raises :class:`InvalidTokenError`, and a
fresh nonce per call makes ciphertexts non-deterministic.

# PARKED: a ``cryptography.Fernet`` / libsodium backend (the spec's preferred
# implementation) is not exercised here because those packages are not installed
# and ``uv sync`` is disallowed in this phase. :class:`FernetCipher` below is the
# drop-in production seam; it imports ``cryptography`` lazily and is intentionally
# left untested in this sandbox. See MORNING_REPORT.
"""

from __future__ import annotations

import hashlib
import hmac
import os
import secrets
import struct
from typing import Protocol, runtime_checkable

#: Wire format version (first byte of every blob) — lets the format evolve.
VERSION = 1
NONCE_SIZE = 16
TAG_SIZE = 32
_MIN_KEY_SIZE = 16
_HEADER_SIZE = 1 + NONCE_SIZE + TAG_SIZE  # version + nonce + tag

_ENC_CONTEXT = b"forge-secret-enc-v1"
_MAC_CONTEXT = b"forge-secret-mac-v1"


class InvalidTokenError(Exception):
    """Raised when a blob fails authentication or cannot be parsed.

    Deliberately uniform: callers cannot distinguish a wrong key, a tampered
    ciphertext, or a malformed blob (avoids an oracle).
    """


@runtime_checkable
class SecretCipher(Protocol):
    """Minimal cipher surface the vault depends on (swappable backend)."""

    def encrypt(self, plaintext: str) -> bytes: ...

    def decrypt(self, blob: bytes) -> str: ...


def generate_key() -> bytes:
    """Return a fresh 32-byte master key suitable for :class:`HmacAeadCipher`."""
    return secrets.token_bytes(32)


def _derive(master: bytes, context: bytes, nonce: bytes) -> bytes:
    """Derive a 32-byte subkey from the master key, context, and nonce."""
    return hmac.new(master, context + nonce, hashlib.sha256).digest()


def _keystream(enc_key: bytes, nonce: bytes, length: int) -> bytes:
    """HMAC-SHA256 counter-mode keystream of ``length`` bytes."""
    out = bytearray()
    counter = 0
    while len(out) < length:
        block = hmac.new(
            enc_key, nonce + struct.pack(">I", counter), hashlib.sha256
        ).digest()
        out.extend(block)
        counter += 1
    return bytes(out[:length])


def _xor(data: bytes, stream: bytes) -> bytes:
    return bytes(a ^ b for a, b in zip(data, stream, strict=True))


class HmacAeadCipher:
    """Standard-library authenticated encryption (encrypt-then-MAC).

    The ``key`` is the workspace/instance master key (>= 16 bytes; use
    :func:`generate_key` for 32 random bytes).
    """

    def __init__(self, key: bytes) -> None:
        if len(key) < _MIN_KEY_SIZE:
            raise ValueError(
                f"master key must be at least {_MIN_KEY_SIZE} bytes, got {len(key)}"
            )
        self._key = bytes(key)

    def encrypt(self, plaintext: str) -> bytes:
        nonce = os.urandom(NONCE_SIZE)
        enc_key = _derive(self._key, _ENC_CONTEXT, nonce)
        mac_key = _derive(self._key, _MAC_CONTEXT, nonce)
        pt = plaintext.encode("utf-8")
        ct = _xor(pt, _keystream(enc_key, nonce, len(pt)))
        header = bytes([VERSION]) + nonce
        tag = hmac.new(mac_key, header + ct, hashlib.sha256).digest()
        return header + tag + ct

    def decrypt(self, blob: bytes) -> str:
        if len(blob) < _HEADER_SIZE or blob[0] != VERSION:
            raise InvalidTokenError("malformed or unsupported secret blob")
        nonce = blob[1 : 1 + NONCE_SIZE]
        tag = blob[1 + NONCE_SIZE : _HEADER_SIZE]
        ct = blob[_HEADER_SIZE:]
        mac_key = _derive(self._key, _MAC_CONTEXT, nonce)
        expected = hmac.new(mac_key, blob[:1] + nonce + ct, hashlib.sha256).digest()
        if not hmac.compare_digest(tag, expected):
            raise InvalidTokenError("authentication failed (wrong key or tampered)")
        enc_key = _derive(self._key, _ENC_CONTEXT, nonce)
        pt = _xor(ct, _keystream(enc_key, nonce, len(ct)))
        try:
            return pt.decode("utf-8")
        except UnicodeDecodeError as exc:  # pragma: no cover - guarded by MAC
            raise InvalidTokenError("decrypted payload is not valid UTF-8") from exc


class FernetCipher:  # pragma: no cover
    """Production seam: ``cryptography.Fernet``-backed cipher.

    # PARKED: ``cryptography`` is not installed in this build sandbox and
    # ``uv sync`` is disallowed, so this adapter is not import-loaded or tested
    # here. Swap it in for :class:`HmacAeadCipher` once the dependency is present;
    # the :class:`SecretCipher` surface is identical.
    """

    def __init__(self, key: bytes) -> None:
        from cryptography.fernet import Fernet

        self._fernet = Fernet(key)

    def encrypt(self, plaintext: str) -> bytes:
        return self._fernet.encrypt(plaintext.encode("utf-8"))

    def decrypt(self, blob: bytes) -> str:
        from cryptography.fernet import InvalidToken

        try:
            return self._fernet.decrypt(blob).decode("utf-8")
        except InvalidToken as exc:
            raise InvalidTokenError("authentication failed (wrong key or tampered)") from exc


__all__ = [
    "FernetCipher",
    "HmacAeadCipher",
    "InvalidTokenError",
    "SecretCipher",
    "generate_key",
]
